### ISSUE TITLE
conda: document environment files

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-doc#281]
We should document some example Cylc stack installations in the form of Conda environment files.

See https://github.com/cylc/cylc-admin/issues/130

As an added bonus we could build these environments as part of the test battery to make sure they don't break.

**Comment by oliver-sanders** [comment]
We should include details/examples of the following options:

* Python (setting version number).
* JupyterHub (now optional via pip, soon to be a separate output on conda).
* Configurable HTTP Proxy (optional for JupyterHub via conda, alternatives exist).
* Jupyter Lab.
* Jupyter Lab / Hub plugins.
* Rose / Cylc Rose.

**Comment by wxtim** [comment]
>     * Python (setting version number).

Easy to add. Will do. 

>     * JupyterHub (now optional via pip, soon to be a separate output on conda).
> 
>     * Configurable HTTP Proxy (optional for JupyterHub via conda, alternatives exist).
> 
>     * Jupyter Lab.
> 
>     * Jupyter Lab / Hub plugins.
 
I don't know very much about these things. Will @datamel  be able to fill me in?

>     * Rose / Cylc Rose.

Done this

**Comment by oliver-sanders** [comment]
I'll try to take a stab at the JupyterHub and Configurable HTTP Proxy stuff when we make the next release (not resolved yet).

The Lab stuff is literally just adding `jupyterlab` into the Conda deps list (no version required).

**Comment by wxtim** [comment]
O.K. I'll add the differing python versions and JupyterLab and flesh out the docs a little by adding the commands used to create the nvs then leave the rest for now.

**Comment by oliver-sanders** [comment]
Closed by https://github.com/cylc/cylc-doc/pull/342
